server:
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: false
spring:
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        formate_sql: true
    open-in-view: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      idle-timeout: 30000
      max-lifetime: 30000
    url: jdbc:mariadb://127.0.0.1:33060/test
    username: root
    password: dnjsehddus